// src/pages/manager/SalarySlip.jsx
import { useState, useEffect } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { SalSlipService } from "../../api/SalSlipService";
import { GovCard } from "../../components/ui/GovCard";
import { GovButton } from "../../components/ui/GovButton";
import { GovBadge } from "../../components/ui/GovBadge";
import {
  GovTable,
  GovTableHeader,
  GovTableRow,
  GovTableCell,
} from "../../components/ui/GovTable";
import { FileText, ChevronLeft, ChevronRight, Download } from "lucide-react";

export function ManagerSalarySlips() {
  const { user } = useAuth();

  const [slips, setSlips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalRecords, setTotalRecords] = useState(0);
  const pageSize = 15;

  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  useEffect(() => {
    // Only fetch if we have a valid department_id from the logged-in manager
    if (user?.department_id) {
      fetchSlips();
    } else {
      setLoading(false);
      setError("Department access restricted or not found.");
    }
  }, [currentPage, user]);

  const fetchSlips = async () => {
    setLoading(true);
    setError(null);
    try {
      // Pass the manager's department_id to filter the API request
      const data = await SalSlipService.getSalarySlipList(
        currentPage,
        pageSize,
        {
          department_id: user.department_id,
        },
      );
      setSlips(data.results || []);
      setTotalRecords(data.count || 0);
      setTotalPages(Math.ceil((data.count || 0) / pageSize) || 1);
    } catch (err) {
      console.error("Failed to fetch salary slips:", err);
      setError(
        "Unable to load department salary slips. Please try again later.",
      );
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (slip) => {
    try {
      await SalSlipService.downloadSalarySlip(
        slip.employee_code,
        slip.slip_year,
        slip.slip_month,
      );
    } catch (err) {
      alert("Failed to download the salary slip.");
    }
  };

  const getStatusVariant = (status) => {
    switch (status?.toUpperCase()) {
      case "GENERATED":
        return "success";
      case "DISPATCHED":
        return "primary";
      case "DRAFT":
      default:
        return "neutral";
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
            <FileText className="text-primary-dark" size={24} />
            Department Salary Slips
          </h2>
          <p className="text-sm text-gray-500">
            View and download historical salary records for your team.
          </p>
        </div>
      </div>

      <GovCard className="p-0 overflow-hidden border-gray-200">
        <div className="p-5 border-b border-gray-200 flex justify-between items-center bg-gray-50">
          <h3 className="font-semibold text-gray-700">Team Salary Directory</h3>
          <span className="text-sm text-gray-500 font-medium">
            Total Records: {totalRecords}
          </span>
        </div>

        {error ? (
          <div className="p-8 text-center text-danger font-medium">{error}</div>
        ) : loading ? (
          <div className="p-12 flex justify-center items-center">
            <div className="w-8 h-8 border-4 border-blue-200 border-t-primary-dark rounded-full animate-spin"></div>
          </div>
        ) : slips.length === 0 ? (
          <div className="p-12 text-center text-gray-500">
            No salary slips have been generated for your department yet.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <GovTable className="border-0">
              <GovTableHeader>
                <GovTableCell isHeader>Slip Number</GovTableCell>
                <GovTableCell isHeader>Employee</GovTableCell>
                <GovTableCell isHeader>Period</GovTableCell>
                <GovTableCell isHeader>Net Pay</GovTableCell>
                <GovTableCell isHeader>Status</GovTableCell>
                <GovTableCell isHeader>Generated By</GovTableCell>
                <GovTableCell isHeader>Generated At</GovTableCell>
                <GovTableCell isHeader className="text-right">
                  Actions
                </GovTableCell>
              </GovTableHeader>
              <tbody>
                {slips.map((slip) => (
                  <GovTableRow key={slip.id}>
                    <GovTableCell className="font-mono text-xs font-medium text-gray-600">
                      {slip.slip_number}
                    </GovTableCell>
                    <GovTableCell>
                      <div className="font-medium text-gray-800">
                        {slip.employee_name}
                      </div>
                      <div className="text-xs text-gray-500 font-mono">
                        {slip.employee_code} • {slip.department_name}
                      </div>
                    </GovTableCell>
                    <GovTableCell className="font-medium text-gray-700">
                      {monthNames[slip.slip_month - 1]} {slip.slip_year}
                    </GovTableCell>
                    <GovTableCell className="font-semibold text-green-700">
                      ₹{parseFloat(slip.net_pay).toLocaleString("en-IN")}
                    </GovTableCell>
                    <GovTableCell>
                      <GovBadge variant={getStatusVariant(slip.status)}>
                        {slip.status}
                      </GovBadge>
                    </GovTableCell>
                    <GovTableCell className="text-sm text-gray-600">
                      {slip.generated_by_name}
                    </GovTableCell>
                    <GovTableCell className="text-xs text-gray-500">
                      {slip.generated_at
                        ? new Date(slip.generated_at).toLocaleString()
                        : "N/A"}
                    </GovTableCell>
                    <GovTableCell className="text-right">
                      <GovButton
                        variant="outline"
                        size="sm"
                        className="gap-2"
                        onClick={() => handleDownload(slip)}
                      >
                        <Download size={14} /> PDF
                      </GovButton>
                    </GovTableCell>
                  </GovTableRow>
                ))}
              </tbody>
            </GovTable>
          </div>
        )}

        {/* Pagination Controls */}
        {!loading && !error && totalPages > 1 && (
          <div className="flex items-center justify-between px-5 py-3 border-t border-gray-200 bg-gray-50">
            <p className="text-sm text-gray-600">
              Showing page <span className="font-bold">{currentPage}</span> of{" "}
              <span className="font-bold">{totalPages}</span>
            </p>
            <div className="flex gap-2">
              <GovButton
                variant="secondary"
                size="sm"
                onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="gap-1"
              >
                <ChevronLeft size={16} /> Prev
              </GovButton>
              <GovButton
                variant="secondary"
                size="sm"
                onClick={() =>
                  setCurrentPage((p) => Math.min(totalPages, p + 1))
                }
                disabled={currentPage === totalPages}
                className="gap-1"
              >
                Next <ChevronRight size={16} />
              </GovButton>
            </div>
          </div>
        )}
      </GovCard>
    </div>
  );
}

export default ManagerSalarySlips;
